server:
  port: 8866
spring:
  application:
    name: tulingmall-product
  mvc:
    pathmatch:
      matchingStrategy: ANT_PATH_MATCHER


  main:
    allow-circular-references: true
seata:
  application‐id: ${spring.application.name}
  # seata 服务分组，要与服务端配置service.vgroup_mapping的后缀对应
  tx‐service‐group: mallv5
  registry:
    # 指定nacos作为注册中心
    type: nacos
    nacos:
      application: seata-server
      server‐addr: 127.0.0.1:8848
      group: DEFAULT_GROUP
      username: nacos
      password: nacos
      cluster: DEFAULT


  config:
    # 指定nacos作为配置中心
    type: nacos
    nacos:
      server‐addr: 127.0.0.1:8848
      group: SEATA_GROUP
      data‐id: seataServer.properties
      username: nacos
      password: nacos
mybatis:
  mapper-locations:
    - classpath*:com/**/mapper/*.xml
    - classpath:dao/*.xml
zk:
  curator:
    retryCount: 3
    elapsedTimeMs: 60
    connectUrl: localhost:2181
    sessionTimeOutMs: 600
    connectionTimeOutMs: 30

