
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

tuling:
    jwt:
      keyPairName: jwt.jks
      keyPairAlias: jwt
      keyPairSecret: lyd0821666
      keyPairStoreSecret: lyd0821666
server:
  port: 9999


