server:
  port: 8054
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/dbase?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: lyd0821666
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#      cluster-nodes: tl.es.com:9300
#      cluster-name: elasticsearch
  application:
    name: tulingmall-search
#  data:
#    elasticsearch:
#      rest:
#        #uris: 192.168.21.110:9300,192.168.21.113:9300,192.168.21.219:9300
#        uris: 192.168.21.219:9300
#        username: elastic
#        password: 123456


mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml




